openapi: 3.0.1
# Added by API Auto Mocking Plugin
servers:
  - description: Development server 
    url: http://localhost:8080
info:
  version: "1.0.0"
  title: MyTogAPI
  description: Let's make life of the photographers awesome!
security:
  - accessCode:
      - read
      - write
paths:
  /example:
    get:
      summary: Server example operation
      description: >-
        This is an example operation to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      security: []
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://mytog.auth0.com/oauth/auth'
          tokenUrl: 'http://mytog.auth0.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources